export const isIos = () => /(iPhone|iPad|iPod)/.test(navigator.platform)

export const filterIOSVoices = (voices) => {
  let selectableVoices = [
    'Maged',
    'Zuzana',
    'Sara',
    'Anna',
    'Melina',
    'Karen',
    'Samantha',
    'Daniel',
    'Rishi',
    'Moira',
    'Tessa',
    'Mónica',
    'Paulina',
    'Satu',
    'Amélie',
    'Thomas',
    'Carmit',
    'Lekha',
    'Mariska',
    'Damayanti',
    'Alice',
    'Kyoko',
    'Yuna',
    'Ellen',
    'Xander',
    'Nora',
    'Zosia',
    'Luciana',
    'Joana',
    'Ioana',
    'Milena',
    'Laura',
    'Alva',
    'Kanya',
    'Yelda',
    'Tian-Tian',
    'Sin-Ji',
    'Mei-Jia'
  ]
  return voices.filter(v => selectableVoices.includes(v.name))
}
